version: '0.1'
services:
  webapp:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mediadb
      POSTGRES_USER: user
      POSTGREST_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgressql/data
volumes:
  db_data:
