services:
  app:
    build: .
    ports:
      - "${PORT:-9001}:${PORT:-9001}"
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-dictdb}
      PORT: ${PORT:-80}
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-dictdb}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      # - ./init:/var/lib/postgressql/data
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
volumes:
  db_data:
